### ISSUE TITLE
Title Bar can't work as normal

### ISSUE THREAD

**Issue by ChenYiLins** [microsoft/WinUI-Gallery#1364] opened 2023-09-26 14:55 UTC
### Which version of the app?

WinUI 3 Gallery

### Description

- The foreground color controls do not work, I think because use new `ExtendsContentIntoTitleBar = true;`
- I don't think the background color meets the definition of color in the Winows application. I even think that the application of system setup in win11 23h2 is a kind of error. The background color of the button hovered in the title bar in dark mode should be light gray (close to white), not dark gray (close to black).

> https://learn.microsoft.com/en-us/windows/apps/design/style/color

- The buttons in the title bar do not have the same fade-in and fade-out effect as the WinUI app created by C++/WinRT when entering and leaving.
- The titile bar foreground color can't change when I change app theme, when theme change  to dark from light, but tiltle foreground color still is white. When I was developing with Template Studio, I could change the foreground color of the title bar control when a theme change was detected. `App.MainWindow.AppWindow.TitleBar.ForegroundColor `

### Screenshots

![image](https://github.com/microsoft/WinUI-Gallery/assets/59414880/453b2975-22a6-4dbc-aadb-5a7192118dbf)
![image](https://github.com/microsoft/WinUI-Gallery/assets/59414880/77ddab1f-5284-4397-b6c9-9fc901393140)

### Windows version

Windows 11 22H2 (22621)

### Additional context

These issues were found in WinUI 3 Gallery version 2.2.0.0.

**Comment by Jay-o-Way** [comment] 2023-10-22 23:07
Looks like https://github.com/microsoft/microsoft-ui-xaml/issues/8899

**Comment by karkarl** [comment] 2023-10-26 18:26
Resolving as duplicate of above xaml bug.

**Closed by karkarl** 2023-10-26 18:26 UTC
Labels: bug
