### ISSUE TITLE
Using the icons search box while an icon is selected crashes the application

### ISSUE THREAD

**Issue by brunt-toast** [microsoft/WinUI-Gallery#1526] opened 2024-04-19 12:07 UTC
### Which version of the app?

WinUI 3 Gallery

### Description

In version 2.4.1.0, the DesignGuidance/ItemsPage.xaml contains an ItemsView named "IconsItemsView". Selecting one of the icons in the list and then using the search bar in any way crashes the application. 

I have observed this issue when installing from the Microsoft Store on multiple devices, but have been unable to recreate with a debugger attached when compiling from source. 

### Windows version

Windows 11 23H2 (22631)

**Comment by karkarl** [comment] 2024-04-25 18:27
Resolving as dupe of #1500

**Closed by karkarl** 2024-04-25 18:27 UTC
Labels: bug, fixed in repo - will be in next update
