### ISSUE TITLE
Gallery crashes when trying to search for an icon a second time

### ISSUE THREAD

**Issue by szaaamerik** [microsoft/WinUI-Gallery#1536] opened 2024-05-14 18:12 UTC
### Which version of the app?

WinUI 3 Gallery

### Description

When initially accessing the icons page and performing a search for an icon, everything functions properly. However, upon attempting to repeat the process, the application crashes.

### Screenshots

https://github.com/microsoft/WinUI-Gallery/assets/126014478/f4fbd2b9-8699-4fe9-9554-f50a99b110b7

### Windows version

Windows 11 23H2 (22631)

### Additional context

I installed the app from the Microsoft Store yesterday.

**Comment by Ferbmr** [comment] 2024-05-15 23:42
did your version crashes too when access to settings? I have latest version (2.4.1 Mar 2024) running on Win11 Pro 23H2 Build 22631.3527

**Comment by szaaamerik** [comment] 2024-05-16 06:35
> did your version crashes too when access to settings? I have latest version (2.4.1 Mar 2024) running on Win11 Pro 23H2 Build 22631.3527



yes, but this is not an issue when I build the app myself.
not sure about the icons though, as I don't have the repository cloned right now.

**Comment by karkarl** [comment] 2024-05-16 18:10
Resolving as dupe of #1500

**Closed by karkarl** 2024-05-16 18:10 UTC
Labels: bug, needs-triage
