### ISSUE TITLE
Gallery crash speedrun

### ISSUE THREAD

**Issue by Petrarca181** [microsoft/WinUI-Gallery#1619] opened 2024-09-02 08:52 UTC
### Which version of the app?
Last(store)

WinUI 3 Gallery

### Description

![363515761-6b25266a-5109-4af1-96db-d39b07dcde8c](https://github.com/user-attachments/assets/506b1702-fe6e-4723-901e-310fc000f18a)
![363519219-378b1505-6cd5-4716-a954-fe240a583cd6](https://github.com/user-attachments/assets/fc8e4382-1ddc-4718-ac51-6c5c923c09ed)
![363519226-83b8fec9-5a18-4a3c-b5ab-8d448718e578](https://github.com/user-attachments/assets/0d769081-bf8d-409f-8050-38a5f4308061)

### Windows version

Windows 11 24H2 (26052)

**Comment by karkarl** [comment] 2024-09-05 18:12
Thanks for filing this bug! Resolving as dupe of #1464

**Closed by karkarl** 2024-09-05 18:12 UTC
Labels: bug, needs-triage
