### ISSUE TITLE
Clicking on a control in the "What's New" page does not update the NavView

### ISSUE THREAD

**Issue by gregwoo-microsoft** [microsoft/WinUI-Gallery#845] opened 2022-01-21 00:32 UTC
**Steps to reproduce the bug**

1) click "what's new"
2) click i.e. "pipspager" from the list

The PipsPager page is loaded but the NavView on the left does not get updated and "what's new" is still selected. So clicking on "what's new" causes no action.

**Expected behavior**
Clicking on a "What's new" control should update the NavView to open at the correct spot (where the control is located).

**Actual behavior**

**Screenshots**

**Version Info**
- [ ] Xaml Controls Gallery - Downloaded from Store
    - If so, which version? (1.2.x -- Found on the Settings page of the app.)
- [x] WinUI 3 Controls Gallery - Downloaded from Store 
    - If so, which version? (1.3.x -- Found on the Settings page of the app.)
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3 branch)

**Additional context**

Windows version:
- [ ] Insider Build (xxxxx)
- [ ] May 2021 Update (19043)
- [ ] October 2020 Update (19042)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [ ] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by bpulliam** [comment] 2022-10-12 01:28
Duplicate of #726 ?

**Comment by niels9001** [comment] 2023-05-16 13:11
This is resolved in the latest version

**Closed by niels9001** 2023-05-16 13:11 UTC
Labels: bug
