### ISSUE TITLE
InvertedListView example not working

### ISSUE THREAD

**Issue by jarlbrak** [microsoft/WinUI-Gallery#1068] opened 2022-09-02 18:57 UTC
### Which version of the app?

WinUI 3 Gallery

### Description

Following the example in the latest version of Windows App SDK does not produce the same results as in the WinUI3 Gallery App.

### Screenshots

XAML code as provided in the example produces this:

```xaml
<DataTemplate x:Key="MessageViewTemplate" x:DataType="local1:Message">
    <Grid Height="Auto" Margin="4" HorizontalAlignment="{x:Bind MsgAlignment}">
        <StackPanel MinHeight="75" Width="350" Padding="10, 0, 0, 10" Background="{x:Bind BgColor}" CornerRadius="{StaticResource ControlCornerRadius}">
            <TextBlock Text="{x:Bind MsgText}" Padding="0, 10, 0, 0" FontSize="20" Foreground="{ThemeResource SystemControlForegroundAltHighBrush}"/>
            <TextBlock Text="{x:Bind MsgDateTime}" Padding="0, 0, 0, 10" FontSize="15" Foreground="{ThemeResource SystemControlForegroundAltMediumHighBrush}"/>
        </StackPanel>
    </Grid>
</DataTemplate>
```

![image](https://user-images.githubusercontent.com/12104244/188219048-7a924493-579f-418c-9d76-a2ca70fbc099.png)

XAML code corrected (not a direct replacement, for my implementation):

```xaml
<DataTemplate x:Key="MessageViewTemplate" x:DataType="models:StatusMessage">
    <Grid Height="Auto" Margin="4" Width="350">
        <StackPanel MinHeight="60" MinWidth="150" Padding="10, 0, 0, 10" Background="{x:Bind Background, Mode=OneWay}" CornerRadius="10" HorizontalAlignment="{x:Bind Alignment, Mode=OneWay}">
            <TextBlock Text="{x:Bind MessageText, Mode=OneWay}" Padding="0, 10, 0, 0" FontSize="16" Foreground="{ThemeResource SystemControlForegroundAltHighBrush}"/>
            <TextBlock Text="{x:Bind MessageTime, Mode=OneWay}" Padding="0, 0, 0, 10" FontSize="10" Foreground="{ThemeResource SystemControlForegroundAltMediumHighBrush}"/>
        </StackPanel>
    </Grid>
</DataTemplate>
```

![image](https://user-images.githubusercontent.com/12104244/188219384-13e98b10-1d1e-4c55-9c57-ede2faa51109.png)

Issues corrected:

1. HorizontalAlignment was set on the grid instead of the stackpanel
2. Width was set on the stackpanel instead of the grid

Not sure how the app works as intended but I could not produce the same results in the latest Windows App SDK version.

### Windows version

November 2021 Update/21H2 (19044)

**Comment by chingucoding** [comment] 2023-10-14 15:11
Thank you for your feedback! I'm afraid though, this is not a bug since the XAML Code shown in the gallery is the same as the code that is powering the sample you are seeing there. The only thing that was out of date were the colors which will be adjusted by #1383. Hence I'll close this issue, if you feel this is an issue, feel free to reopen this issue.

**Closed by chingucoding** 2023-10-14 15:11 UTC
Labels: bug
