### ISSUE TITLE
WinUI 3 Gallery Crash in ```AutoSuggestBox``` Page

### ISSUE THREAD

**Issue by ShimizuTheLotus** [microsoft/WinUI-Gallery#1609] opened 2024-08-16 07:35 UTC
### Which version of the app?

WinUI 3 Gallery

### Description

In the page of ```AutoSuggestBox```, if we type something in the second ```AutoSuggestBox``` and then press ```Enter```, the app will crash.

**Comment by AndrewKeepCoding** [comment] 2024-08-16 12:21
Duplicate of #1581 which was closed with #1582.

**Closed** 2024-08-16 13:22 UTC
Labels: bug, needs-triage

**Comment by marcelwgn** [comment] 2024-08-22 08:19
Thank you @ShimizuTheLotus none the less and thank you @AndrewKeepCoding for stepping in!
