### ISSUE TITLE
WInUI3 Gallery - link to documentation Button - API is broken

### ISSUE THREAD

**Issue by RossCoeH** [microsoft/WinUI-Gallery#990] opened 2022-06-05 00:29 UTC
**Describe the bug**
In Button Example - click on link for  documentation link **Button -API**
get browser link of:
https://docs.microsoft.com/en-nz/windows/winui/api/microsoft.ui.xaml.controls.button 
The page is not found  =error 404 Page not Found

**Steps to reproduce the bug**

As above

**Expected behavior**
Expect to see the doucumentation for Button API

**Actual behavior**
get browser link of:
https://docs.microsoft.com/en-nz/windows/winui/api/microsoft.ui.xaml.controls.button 
The page is not found  =error 404 Page not Found

**Screenshots**

![image](https://user-images.githubusercontent.com/30205634/172029884-46129b13-027f-43a1-bcf4-716c2bc71ea0.png)

**Version Info**

Gallery version (found on Settings page): 
 Version: 1.3.12.0 

WinUI version:
- [ ] WinUI3 / WinAppSDK 1.1
- [ ] WinUI3 / WinAppSDK 1.0
- [ ] WinUI2

Windows 11 version:
- [ ] Insider Build (xxxxx)
- [ ] Windows 11 22H2 (22621)
- [ ] Windows 11 21H2 (22000)

Windows 10 version:
- [ ] November 2021 Update/21H2 (19044)
- [ ] May 2021 Update/21H1 (19043)
- [ ] October 2020 Update/20H2 (19042)
- [ ] October 2018 Update/RS5 (17763)

Device form factor:
- [ ] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by chingucoding** [comment] 2022-06-05 17:04
This seems to be a duplicate of #987, @RossCoeH please let me know if my I understood the bug report correctly :)

**Comment by navarone77** [comment] 2022-06-06 20:15
> 

The issue is the same and still persisting on new updated version.
![image](https://user-images.githubusercontent.com/97413201/172240921-170e3164-dcae-4604-99df-154280a7bdfa.png)

**Comment by chingucoding** [comment] 2022-06-07 16:42
To make tracking of this easier, I'll be closing this as duplicate of #987 since that is a catch all for that bug.

**Closed by chingucoding** 2022-06-07 16:42 UTC
