### ISSUE TITLE
DataGrid for WinUI3

### ISSUE THREAD

**Issue by KishlayaSharma** [microsoft/WinUI-Gallery#1076] opened 2022-09-14 05:28 UTC
### Issue type

sample request

### Which version of the app?

WinUI 3 Gallery

### Description

Please provide code for datagrid. Currently there is only a gif animation.

### Screenshots

![2022-09-14 10_58_07-Mahanth _ Microsoft Teams](https://user-images.githubusercontent.com/39042276/190066896-a0463bf5-295f-4203-bbd0-228a18edfd54.png)

### Windows version

Windows 11 22H2 (22621)

**Comment by michael-hawker** [comment] 2022-09-20 19:03
@KishlayaSharma you need to click the link at the bottom to open the [Windows Community Toolkit Sample App](https://aka.ms/windowstoolkitapp), as the control is part of the Windows Community Toolkit.

The WCT sample app has sample code on how to use the DataGrid, as do the [docs](https://aka.ms/windowstoolkitdocs).

**Comment by karkarl** [comment] 2024-01-11 19:18
This should be an issue on community toolkit to re-add the samples and instructions on their gallery app. In fact, the data-grid page in WinUI Gallery should be removed since it's irrelevant and just referring to the community toolkit.

**Comment by michael-hawker** [comment] 2024-01-11 19:26
The DataGrid was not ported to the 8.0 codebase, we don't intend to add new samples for the 7.1 version to our gallery app.

**Comment by karkarl** [comment] 2024-04-18 18:30
Resolving as dupe of #1525

**Closed by karkarl** 2024-04-18 18:30 UTC
Labels: new sample
