### ISSUE TITLE
Unstably Crash when Seatching Icons

### ISSUE THREAD

**Issue by ShimizuTheLotus** [microsoft/WinUI-Gallery#1499] opened 2024-03-16 08:30 UTC
### Which version of the app?

WinUI 3 Gallery

### Description

I was using WinUI 3 Gallery for searching icons and sometimes when I tried to type in the search box, the app will crash(Not every time).

### Screenshots

![image](https://github.com/microsoft/WinUI-Gallery/assets/152269217/9ad1c739-7b5f-4d50-8174-f73bc01fca96)
the search box with letter "A" in it is the target.

### Windows version

Insider Build (xxxxx)

### Additional context

Windows 23H2 (OS Build 22635.3139)
WinUI 3 Gallery 2.4.1.0

**Comment by marcelwgn** [comment] 2024-03-28 18:24
In theory, this should have been fixed with #1461, can you try to run the app from source and see if it still repros?

**Comment by karkarl** [comment] 2024-04-25 18:26
Resolving as dupe of #1500

**Closed by karkarl** 2024-04-25 18:26 UTC
Labels: bug, needs-author-feedback
