### ISSUE TITLE
Fix releases

### ISSUE THREAD

**Issue by gregwoo-microsoft** [microsoft/WinUI-Gallery#1017] opened 2022-06-17 18:58 UTC
### Issue type

enhancement

### Which version of the app?

WinUI 3 Gallery

### Description

- Update repo release process so that a release is only posted on Github when there is a store update

**Comment by karkarl** [comment] 2023-05-03 18:27
Closing - dupe of #1025

**Closed by karkarl** 2023-05-03 18:27 UTC
Labels: enhancement
