### ISSUE TITLE
Filtering icons in Design guiance/Icons crashes the app

### ISSUE THREAD

**Issue by JuanMejiaVelez** [microsoft/WinUI-Gallery#1516] opened 2024-03-30 18:10 UTC
### Which version of the app?

WinUI 3 Gallery

### Description

When filtering icons using the "Search icons" AutoSuggestTextBox the application crashes, either immediately with the first character or the in the second filter modification.

### Windows version

Insider Build (xxxxx)

**Comment by marcelwgn** [comment] 2024-04-04 17:36
Hey, can you check if you are able to reproduce this issue when building the app from the main branch? In theory #1515 should have fixed this so it would be good to know if there is another cause for this crash.

**Comment by bogdan-patraucean** [comment] 2024-04-04 20:52
@marcelwgn I reproduce the issue the following way:

- search for an icon
- copy the glyph
- try to search again
- app crashes

**Comment by marcelwgn** [comment] 2024-04-06 19:09
Thank you for your input @bogdan-patraucean, did you also try to reproduce this using the app built from the latest commit on main branch or did you try it using the store version?

**Comment by bogdan-patraucean** [comment] 2024-04-06 20:10
@marcelwgn, the store version.

**Comment by marcelwgn** [comment] 2024-04-07 20:30
Allright, would you mind checking with a built version from the main branch to see if the fixes work @bogdan-patraucean or if the issue is still present?

**Comment by bogdan-patraucean** [comment] 2024-04-09 18:34
@marcelwgn, the main branch seems to be working fine

**Comment by marcelwgn** [comment] 2024-04-09 20:11
Awesome, thank you for testing this out and helping out that much @bogdan-patraucean! I'll be closing this issue then, since it seems the issue is fixed on main.

**Closed by marcelwgn** 2024-04-09 20:11 UTC
Labels: bug, needs-author-feedback
