### ISSUE TITLE
App immediately stops when a lot of navigation with huge memory leak

### ISSUE THREAD

**Issue by Dimigergo** [microsoft/WinUI-Gallery#1075] opened 2022-09-12 12:11 UTC
### Which version of the app?

WinUI 3 Gallery

### Description

The application immediately exit with the following screenshot when I have a lot of navigation (About 30-40 continously). The memory continously increasing, and freeze when it reaches 400-500 Mb. When I open the layout tab with the images the increasing is higher than the other. 
So I think it is a massive memory leak with the navigation view, but in the other opened memory leak discussion in the microsotf-ui-xaml github talking about few kb-s permitted leak.

### Screenshots

![app_error](https://user-images.githubusercontent.com/11498949/189649079-008b6881-a062-4dd4-b624-73f214b5083a.png)

### Windows version

November 2021 Update/21H2 (19044)

**Comment by chingucoding** [comment] 2023-08-27 16:42
Thank you for reporting this (and sorry for the delayed response). Are you still able to reproduce the app crashing? I tested this while investigating #1318 and while memory usage increases the app did not crash (and also was able to clean itself up if necessary)

**Comment by Dimigergo** [comment] 2023-08-28 06:55
Hello! We have more another development, so not so much time, but I try to test it, but I have time for it.

**Comment by chingucoding** [comment] 2023-10-14 15:13
Closing due to staleness, if you are able to reproduce this issue, feel free to reopen this issue :)

**Closed by chingucoding** 2023-10-14 15:13 UTC
Labels: bug
