### ISSUE TITLE
AutoSuggestBox Bug

### ISSUE THREAD

**Issue by KevinJiaXiangLiu** [microsoft/WinUI-Gallery#1642] opened 2024-11-05 09:33 UTC
### Which version of the app?

WinUI 3 Gallery

### Description

The second AutoSuggestBox may bug.
Control: Text -> AutoSuggestBox -> SearchBox
Bug Operations:
1. Input Text;
2. Press 'up' or 'down' key to select item;
3. Press 'enter' key to select.
4. App will be down.

Using mouse to select item is safe.

版本	Windows 11 家庭中文版
版本号	24H2
安装日期	‎2024/‎10/‎17
操作系统版本	26100.2033
体验	Windows Feature Experience Pack 1000.26100.23.0

### Screenshots

![Image](https://github.com/user-attachments/assets/f63297ae-8ebb-4fd2-bb4c-f0d4f8cc7178)

### Windows version

Windows 11 24H2 (26052)

**Comment by AndrewKeepCoding** [comment] 2024-11-05 12:16
Duplicate of #1581 which was closed with #1582.

**Closed** 2024-11-07 19:07 UTC
Labels: bug, fixed in repo - will be in next update
