### ISSUE TITLE
[Bug] Crash after clicking "Settings"

### ISSUE THREAD

**Issue by Mikachu2333** [microsoft/WinUI-Gallery#1528] opened 2024-04-25 12:59 UTC
### Which version of the app?

WinUI 3 Gallery

### Description

Win10 22h2 (19045.4291), installed in Microsoft Store, VS 2022 has been installed with _.net_ and _cpp desktop_ target.

How could I debug it or upload the log files as a user who is not an expert in programming?

### Screenshots

https://github.com/microsoft/WinUI-Gallery/assets/63829496/3bf31042-ab07-42ab-bd3f-6cb2d93d1cb0

### Windows version

Windows 10 22H2 (19045)

**Comment by Jay-o-Way** [comment] 2024-04-25 13:44
There seems to be an issue with the video - at least for me, at the moment. Can you check it. And also give steps to reproduce in text please. Thanks :)

**Comment by karkarl** [comment] 2024-04-25 18:10
This should be resolved with #1480 soon

**Comment by Jay-o-Way** [comment] 2024-04-25 18:12
Duplicate of #1477

**Comment by karkarl** [comment] 2024-04-25 18:14
@Mikachu2333 To debug a store app, you can try attach to process with Visual Studio: https://learn.microsoft.com/en-us/visualstudio/debugger/attach-to-running-processes-with-the-visual-studio-debugger?view=vs-2022

Let me know if this helps.

**Closed** 2024-04-25 18:14 UTC
Labels: bug, needs-triage
