### ISSUE TITLE
WinUI 3 Gallery has crashed twice in 5 minutes

### ISSUE THREAD

**Issue by Gavin-Williams** [microsoft/WinUI-Gallery#1410] opened 2023-11-29 14:25 UTC
### Which version of the app?

WinUI 3 Gallery

### Description

The app seems to be really unstable, I'm just looking around through the examples and it's crashing.

### Windows version

Windows 11 22H2 (22621)

**Comment by AndrewKeepCoding** [comment] 2023-12-07 00:22
Might be related to #1356.

**Comment by karkarl** [comment] 2024-09-05 18:10
Resolving as dupe of #1464

**Closed by karkarl** 2024-09-05 18:10 UTC
Labels: bug
