### ISSUE TITLE
Add StyleCop

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/WinUI-Gallery#414] opened 2020-04-23 17:00 UTC
**Describe the bug**
Would be great to ensure consistency for samples/helper code to have StyleCop enabled on the project.

**Comment by chingucoding** [comment] 2020-06-27 22:09
Sounds like a great idea! I've added the StyleCop package to check how much we would need to do and, we got over 4400 warnings :/

Adding this and fixing all those warnings will probably be a lot of work.

**Comment by karkarl** [comment] 2024-02-22 19:25
Resolving this as dupe of #1279.

**Closed by karkarl** 2024-02-22 19:25 UTC
Labels: enhancement
