### ISSUE TITLE
App crashes when you press ENTER in the search bar in the NavigationView

### ISSUE THREAD

**Issue by nikolayvpavlov** [microsoft/WinUI-Gallery#1469] opened 2024-03-01 12:59 UTC
### Which version of the app?

WinUI 3 Gallery

### Description

Type some text in the search bar of the Navigation View, and press ENTER.  The application crashes and closes itself. The following error can be found in the Event Log:

Faulting application name: WinUIGallery.exe, version: 2.4.0.0, time stamp: 0x65a70000
Faulting module name: Microsoft.ui.xaml.dll, version: 3.1.5.0, time stamp: 0x1048d178
Exception code: 0xc000027b
Fault offset: 0x0000000000404275

### Windows version

Windows 11 22H2 (22621)

**Comment by karkarl** [comment] 2024-04-11 18:28
What version of WinUI Gallery is this? This should be fixed with this commit: https://github.com/microsoft/WinUI-Gallery/commit/bf8f076c9df47ebe08e68a96f4a4cb086af48da5

Dupe of #1438

**Closed by karkarl** 2024-04-11 18:28 UTC
Labels: bug, needs-triage
