### ISSUE TITLE
ProgressBar isn't running when its page loads

### ISSUE THREAD

**Issue by YuliKl** [microsoft/WinUI-Gallery#365] opened 2020-02-28 21:23 UTC
**Describe the bug**

Although the ProgressBar's state radio button is set to "Running" on page load, the control isn't animating. 

**Steps to reproduce the bug**

1. Navigate to the ProgressBar page
2. Observe that indeterminate progress bar is not moving

**Expected behavior**

The running animation should play

**Actual behavior**

Progress bar appears to be paused

**Screenshots**

![image](https://user-images.githubusercontent.com/13142665/75588425-7fa88480-5a2d-11ea-80f7-7fa320cf74ae.png)

**Version Info**

Gallery version (found on Settings page): 

1.2.13.0

**Comment by chingucoding** [comment] 2020-02-28 23:21
I have the feeling that this is an issue with the ProgressBar control. No matter what values I set, the ProgressBar does not seem to start its animation unless we change a value with some delay. Creating it and immediately changing `IsIndeterminate` or `ShowPaused` also doesn't seem to fix this.

**Comment by chingucoding** [comment] 2020-03-24 19:08
It seems that with the latest WinUI preview, the progressbar is running when navigating to the page, so this issue can be closed now.

**Comment by chingucoding** [comment] 2022-06-03 22:12
Closing since this does not reproduce in either versions of the WinUI gallery.

**Closed by chingucoding** 2022-06-03 22:12 UTC
