### ISSUE TITLE
Changing the settings of the title bar makes it completely inactive

### ISSUE THREAD

**Issue by wnstngs** [microsoft/WinUI-Gallery#959] opened 2022-05-19 17:06 UTC
**Describe the bug**
After changing the settings of the title bar (color of the background and foreground, reset to the system title bar, and turn back to custom) I ran into a problem. The title bar stopped handling any mouse events (dragging a window or clicking buttons) as if it were covered by some invisible element.

**Steps to reproduce the bug**

1. Navigate to 'Windows' -> 'Titlebar'
2. Play with title bar settings
3. Set custom title bar
4. Try to move the window or close it

**Expected behavior**
The window is draggable and the title bar button works.

**Actual behavior**
The custom title bar doesn't handle any events.

**Version Info**
1.3.11.0
Windows 10 19044.1706

Gallery version (found on Settings page): 
1.3.11.

**Comment by gregwoo-microsoft** [comment] 2022-05-20 07:22
Hi @wnstngs! Thank you for filing this issue. We are aware of this bug and currently working to get it fixed. Thank you for taking the time to file this though! :)

**Comment by chingucoding** [comment] 2022-10-01 06:17
I'm unable to reproduce this @wnstngs, are you still able to reproduce this?

**Comment by bpulliam** [comment] 2022-10-11 22:45
We've made a number of fixes to the titlebar.  I'm marking it as Fixed in Repo, as I believe the 1.2 upgrade and the other changes have fixed this issue.

**Closed** 2023-05-16 13:08 UTC
Labels: bug
