### ISSUE TITLE
Switching between multiple tabs repeatedly causes the WinUI 3 Gallery to crash.

### ISSUE THREAD

**Issue by huguojunsy** [microsoft/WinUI-Gallery#1621] opened 2024-09-10 03:25 UTC
### Which version of the app?

WinUI 3 Gallery

### Description

Switching between multiple tabs repeatedly causes the WinUI 3 Gallery to crash.
[https://github.com/microsoft/microsoft-ui-xaml/discussions/9417#discussioncomment-10514181](url)

**Comment by huguojunsy** [comment] 2024-09-10 03:34
![363519226-83b8fec9-5a18-4a3c-b5ab-8d448718e578](https://github.com/user-attachments/assets/1537bf76-e9d6-45a6-84da-9717375b325f)
![363519219-378b1505-6cd5-4716-a954-fe240a583cd6](https://github.com/user-attachments/assets/99fcd411-e1e9-4ca5-ba57-d472521523d4)
![363515761-6b25266a-5109-4af1-96db-d39b07dcde8c](https://github.com/user-attachments/assets/d627bf87-feb4-4ce5-9eac-e15fdc281ec0)

**Comment by karkarl** [comment] 2024-09-12 18:27
Resolving as dupe of #1464

**Closed by karkarl** 2024-09-12 18:27 UTC
Labels: bug, needs-triage
