### ISSUE TITLE
This project is not building when minimum sdk version is set to 1703(build 15063).

### ISSUE THREAD

**Issue by rahulkps23** [microsoft/WinUI-Gallery#425] opened 2020-05-11 10:11 UTC
**Describe the bug**
As per [Microsoft docs for WinUI](https://docs.microsoft.com/en-us/uwp/toolkits/winui/getting-started), WinUi 2.4 should work fine from minimum sdk version 1703. But when i try to build this 'xaml control gallery(version: 1.2.15.0 )' project keeping minimum target version as 1703(as shown in the image attached) it is throwing errors. Thus i am not able to install this app on a 1703 version machine as i am not able to generate a appx for 1703. But the microsoft docs says the minimum version WinUi 2.4 works is 1703, what is the use if this 'xaml control gallery' project which is using WinUi 2.4 doesn't work for 1703.

**Steps to reproduce the bug**
1. open project in visual studio, right click on project and go to properties.
2. In properties set the minimum target version to "windows 10 creators update(build 15063)" i.e, version 1703.
3. Now try to build the project, build fails and throws errors.

**Expected behavior**
The build of project should be successful even when we keep the minimum target version to 1703.

**Actual behavior**
The project's build is not successful for version 1703, but build is successful when minimum target version is set to 1709.
But still when we create a appx package and try to install, the app is not installing on both 1703 and 1709. But as per microsoft docs winui 2.x series should install and work fine from 1703 version.

**Screenshots**
![Screenshot (157)](https://user-images.githubusercontent.com/29331748/81550060-5bf2aa80-939d-11ea-9b8a-719c0d42a2cf.png)

Gallery version (found on Settings page): 
1.2.15.0 

Device form factor:
- Desktop

**Additional context**
we have to make sure that app install on 1703 version also and all the features, controls should work as expected on 1703 verson too. Because WinUi was built for that purpose only i.e., Controls are decoupled from platform to provide support for previous OS versions like 1703, 1709.

**Comment by chingucoding** [comment] 2020-06-06 18:19
@stmoy Seems like that we are using a few C# features that are not available in 1703 but in later versions. Should we make the effort and look for alternatives for those features to support 1703?

**Comment by stmoy** [comment] 2020-06-08 17:23
Let me discuss this internally. We deliberately set the min-version to 1709 but I don't recall the exact motivations.

**Comment by chingucoding** [comment] 2020-06-08 17:46
This is the list of COMPILATION errors:

```
Severity	Code	Description	File	Project	Line	Suppression State
Error	CS1503	Argument 1: cannot convert from 'string' to 'char'	D:\Projects\Xaml-Controls-Gallery\XamlControlsGallery\SearchResultsPage.xaml.cs	XamlControlsGallery	81	Active
Error	CS1503	Argument 1: cannot convert from 'string' to 'char'	D:\Projects\Xaml-Controls-Gallery\XamlControlsGallery\ControlPages\AutoSuggestBoxPage.xaml.cs	XamlControlsGallery	133	Active
Error	CS0117	'StringComparison' does not contain a definition for 'InvariantCultureIgnoreCase'	D:\Projects\Xaml-Controls-Gallery\XamlControlsGallery\ControlPages\ItemsRepeaterPage.xaml.cs	XamlControlsGallery	376	Active
Error	CS1503	Argument 1: cannot convert from 'string' to 'char'	D:\Projects\Xaml-Controls-Gallery\XamlControlsGallery\ControlPages\ListViewPage.xaml.cs	XamlControlsGallery	141	Active
Error	CS1503	Argument 2: cannot convert from 'int' to 'char'	D:\Projects\Xaml-Controls-Gallery\XamlControlsGallery\ControlPages\ListViewPage.xaml.cs	XamlControlsGallery	141	Active
Error	CS0117	'StringComparison' does not contain a definition for 'InvariantCultureIgnoreCase'	D:\Projects\Xaml-Controls-Gallery\XamlControlsGallery\ControlPages\ListViewPage.xaml.cs	XamlControlsGallery	295	Active
Error	CS0117	'StringComparison' does not contain a definition for 'InvariantCultureIgnoreCase'	D:\Projects\Xaml-Controls-Gallery\XamlControlsGallery\ControlPages\ListViewPage.xaml.cs	XamlControlsGallery	296	Active
Error	CS0117	'StringComparison' does not contain a definition for 'InvariantCultureIgnoreCase'	D:\Projects\Xaml-Controls-Gallery\XamlControlsGallery\ControlPages\ListViewPage.xaml.cs	XamlControlsGallery	297	Active
Error	CS0117	'Debug' does not contain a definition for 'Print'	D:\Projects\Xaml-Controls-Gallery\XamlControlsGallery\ControlPages\NavigationViewPage.xaml.cs	XamlControlsGallery	183	Active
Error	CS0308	The non-generic method 'Enum.Parse(Type, string)' cannot be used with type arguments	D:\Projects\Xaml-Controls-Gallery\XamlControlsGallery\ControlPages\RadialGradientBrushPage.xaml.cs	XamlControlsGallery	35	Active
Error	CS0308	The non-generic method 'Enum.Parse(Type, string)' cannot be used with type arguments	D:\Projects\Xaml-Controls-Gallery\XamlControlsGallery\ControlPages\RadialGradientBrushPage.xaml.cs	XamlControlsGallery	40	Active
Error	CS1503	Argument 1: cannot convert from 'string' to 'char'	D:\Projects\Xaml-Controls-Gallery\XamlControlsGallery\Navigation\NavigationRootPage.xaml.cs	XamlControlsGallery	302	Active
Error	CS1503	Argument 1: cannot convert from 'char' to 'string'	D:\Projects\Xaml-Controls-Gallery\XamlControlsGallery\ControlExample.xaml.cs	XamlControlsGallery	265	Active
```

The problem is that those are only the compile time errors. If we are using any API's or features that are not available, essentially we would need to check every file whether there are API's for this or not. I doubt that there are many, but maybe that is the reason why are having a minimum SDK version of 1803.

**Comment by chingucoding** [comment] 2022-06-25 14:52
@gregwoo-microsoft Do you think we should close this given that only the WinUI 2 Gallery exhibits this issue?

**Closed** 2022-07-01 23:16 UTC
Labels: enhancement, winui2
