### ISSUE TITLE
Selecting NavigationView quickly after other menu items crashes the app

### ISSUE THREAD

**Issue by skrubbeltrang** [microsoft/WinUI-Gallery#1414] opened 2023-12-05 14:15 UTC
### Which version of the app?

WinUI 3 Gallery

### Description

Open the left-hand Navigation menu item, then quickly select the NavigationView item while shuffling between the other options.
After a few times the entire app crashes when selecting NavigationView.

### Screenshots

![image](https://github.com/microsoft/WinUI-Gallery/assets/3290140/c7fd2a21-f0c3-4626-8d18-a41db4538ab6)

### Windows version

Windows 10 22H2 (19045)

### Additional context

The following is logged in EventViewer, Application log:

Faulting application name: WinUIGallery.exe, version: 2.2.0.0, time stamp: 0x64b073ea
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3758, time stamp: 0xd80f8f12
Exception code: 0xc000027b
Fault offset: 0x000000000012db22
Faulting process id: 0x7f10
Faulting application start time: 0x01da2784b36c4d0f
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WinUI3ControlsGallery_2.2.0.0_x64__8wekyb3d8bbwe\WinUIGallery\WinUIGallery.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 52a33389-aa16-44f4-bdf2-116fe3c9a770
Faulting package full name: Microsoft.WinUI3ControlsGallery_2.2.0.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

**Comment by karkarl** [comment] 2024-09-05 18:11
Resolving as dupe of #1464

**Closed by karkarl** 2024-09-05 18:11 UTC
Labels: bug
