### ISSUE TITLE
Error running WinUIGallery.DesktopWap

### ISSUE THREAD

**Issue by Jay-o-Way** [microsoft/WinUI-Gallery#1244] opened 2023-04-03 21:41 UTC
### Which version of the app?

WinUI 3 Gallery

### Description

Clone the repo, then open the SLN file in Visual Studio. Then, when I click <kbd>Debug</kbd> on **DesktopWAP** I get an error.

### Screenshots
![image](https://user-images.githubusercontent.com/65828559/229634187-3b53be8b-ec24-4e73-a1a2-0dc7fbc386dc.png)

### Windows version

Windows 10 Pro, 22H2

**Comment by Jay-o-Way** [comment] 2023-04-03 21:51
FYI @Scottj1s

**Comment by Scottj1s** [comment] 2023-04-03 22:14
@Jay-o-Way Looks like you need to install the "Single-project MSIX Packaging Tools for VS 2022" extension to address the MsixPackage error.  I see you're aware of the [NU1201 fix](https://github.com/microsoft/WinUI-Gallery/pull/1243) I checked in earlier, so I assume you have that.  Have you done a clean restore and rebuild?  If the problem persists, can you share a repro?

**Comment by Jay-o-Way** [comment] 2023-04-03 22:43
Hi and thanks for the answer. Seems like I already have that.
![image](https://user-images.githubusercontent.com/65828559/229640777-9f4cd858-7476-4608-8a9d-7c1e061fd91f.png)

After another attempt, WinUIGallery.DesktopWap.Package seems to work. (albeit kinda slow)

**Comment by Scottj1s** [comment] 2023-04-03 23:58
Did you also restart VS and reload your solution?  The error list entries persist.

**Comment by Jay-o-Way** [comment] 2023-04-04 07:55
Seems that 17763 issue is gone now :) The other one (updated main comment) persists...

**Comment by Scottj1s** [comment] 2023-04-04 15:02
@Jay-o-Way glad the 17763 issue is resolved.  

@evelynwu-msft, @bpulliam - any ideas on the MsixPackage launch issue?  In my experience, the cause of that has always been a missing "Single-project MSIX Packaging Tools".  Are there other variables?

**Comment by evelynwu-msft** [comment] 2023-04-04 19:32
Wrong project set as the startup project? Make sure the **`.wapproj`** is selected as the startup project, not the `.csproj`. WinAppSDK apps packaged using a `.wapproj` are (by definition) neither configured for Single-project MSIX Packaging nor can they be `F5`ed in VS.

**Comment by bpulliam** [comment] 2023-04-19 14:20
Did Evelyn's suggestion fix the remaining issue?

**Comment by Jay-o-Way** [comment] 2023-04-20 09:48
Where are those settings? I only used default settings after cloning.
![image](https://user-images.githubusercontent.com/65828559/233328288-11b74f37-d98e-4cb6-abea-a69bd3c2b44f.png)

**Comment by bpulliam** [comment] 2023-04-20 12:58
In the UI you posted, the startup should be WinUIGallery.DesktopWap.Package, not WinUIGallery.DesktopWap. You can also set it in the Solution Explorer, by right-clicking on that package and selecting "Set as Startup Project"

**Comment by Jay-o-Way** [comment] 2023-04-20 14:07
Ohhh I see :) Isn't that the same result as changing this?
![image](https://user-images.githubusercontent.com/65828559/233391858-4de86e61-2d50-4114-abdf-63d8e73bee05.png)
Anyways, I think we're good now :)

**Comment by Scottj1s** [comment] 2023-04-20 16:00
@Jay-o-Way glad you're now unblocked.  If you encounter any other deployment issues, let us know.

**Closed by Scottj1s** 2023-04-20 16:00 UTC
Labels: bug
