### ISSUE TITLE
Support for mouse back and forward buttons 

### ISSUE THREAD

**Issue by jovicde** [microsoft/WinUI-Gallery#1218] opened 2023-03-17 09:01 UTC
### Issue type

enhancement

### Which version of the app?

WinUI 3 Gallery

### Description

Allow to navigate using the back and forward buttons, that many mice have. It would greatly enhance the browsing experience.

### Windows version

November 2021 Update/21H2 (19044)

**Comment by bpulliam** [comment] 2023-03-20 11:57
duplicate of #1205

**Closed by bpulliam** 2023-03-20 11:57 UTC
