### ISSUE TITLE
Switching between GridView and ItemsView crashes the app

### ISSUE THREAD

**Issue by KubaSzostak** [microsoft/WinUI-Gallery#1472] opened 2024-03-04 19:27 UTC
### Which version of the app?

WinUI 3 Gallery

### Description

Switching between `GridView` and `ItemsView` in the navigation view crashes the app.

### Screenshots

![winui-gallery-crash](https://github.com/microsoft/WinUI-Gallery/assets/4609437/98b0328f-016e-48af-a1fa-72206618fbeb)

### Windows version

Windows 10 22H2 (19045)

**Comment by HO-COOH** [comment] 2024-03-18 10:30
Still happens with this release 
![image](https://github.com/microsoft/WinUI-Gallery/assets/42881734/17e15942-8540-4cd1-8706-6da3b7fcf6ab)

**Comment by karkarl** [comment] 2024-04-11 18:24
Sorry for the delay in getting to this bug. I agree, I will frontload and prioritize this bug.

**Comment by karkarl** [comment] 2024-04-11 18:29
Closing as dupe of #1464

**Closed by karkarl** 2024-04-11 18:29 UTC
Labels: bug
