### ISSUE TITLE
Quickly switch between the Navigation View and other view page crash the app

### ISSUE THREAD

**Issue by ReneeGA2020** [microsoft/WinUI-Gallery#1348] opened 2023-08-31 04:39 UTC
### Which version of the app?

WinUI 3 Gallery

### Description

1. Start the gallery app
2. Expand Navigation
3. Use Mouse to quickly switch between BreadcrumbBar and NavigationView page
4. Repeat 3-6 times and you get a crash.

Note: does not have to be BreadcrumbBar, switch between NavigationView page and any other navigation page will crash you.
No crash dialog, the app just disapear.

### Windows version

Windows 11 22H2 (22621)

**Comment by karkarl** [comment] 2023-11-09 19:24
Resolving this as dupe of #1331

**Closed by karkarl** 2023-11-09 19:24 UTC
Labels: bug
