### ISSUE TITLE
C + + + + + + + +

### ISSUE THREAD

**Issue by potionsnotusedlol** [microsoft/WinUI-Gallery#1324] opened 2023-07-24 08:53 UTC
### Issue type

enhancement

### Which version of the app?

WinUI 3 Gallery

### Description

PLEASEEEE  I'm begging you, please just add c++ documentation and some samples in this app. Why do you allow building these UWP apps using C++/WinRT, but no one explaining the way it is done right??! The examples on c# are great but what to do for those who doesn't wanna learn a whole new lang just to use it for current windows development. I'm literally crying rn.

### Windows version

Windows 11 22H2 (22621)

**Comment by chingucoding** [comment] 2023-08-27 16:30
While the request for C++ samples have come multiple times over the years, right now there is no plan on adding C++ samples for different reasons (some being how to maintain the samples and keep the maintainable without having two code bases). 

Maybe you can take a look at this [guide](https://learn.microsoft.com/en-us/windows/apps/get-started/simple-photo-viewer-winui3?tabs=cpp), I found it quite helpful when getting started with WinUI 3 for C++ (though I already had some experience with C++/WinRT beforehand).

**Comment by dr-eck** [comment] 2023-10-25 23:14
Hmm. So programming WinUI 3 with C++/WinRT is "supported", but we don't get example code?  This is very frustrating for those of us who are just beginning C++/WinRT.

**Comment by karkarl** [comment] 2023-11-02 18:16
Closing as dupe of #1323

**Closed by karkarl** 2023-11-02 18:16 UTC
Labels: new sample
