### ISSUE TITLE
WinUI gallery crashes when hovering the first example in AnimationInterop

### ISSUE THREAD

**Issue by RaphMar2021** [microsoft/WinUI-Gallery#1266] opened 2023-04-12 15:49 UTC
### Which version of the app?

WinUI 3 Gallery

### Description

When 0.2 is selected in the first example of the AnimationInterop and the mouse hover the sample button, the app close.

### Windows version

Windows 11 22H2 (22621)

### Additional context

I'm using the app sounds

**Comment by niels9001** [comment] 2023-05-17 08:33
@raphmar2021 I'm trying to repro the issue, but no luck:

![AnimationInterop](https://github.com/microsoft/WinUI-Gallery/assets/9866362/63b4f948-90bd-4813-b5da-cccf1b0538f6)

Are my repro steps correct? Can you confirm that this bug is still present on the latest version of the WinUI 3 Gallery?

**Comment by chingucoding** [comment] 2023-10-03 06:31
Closing due to staleness. If you are able to reproduce, feel free to reopen.

**Closed by chingucoding** 2023-10-03 06:31 UTC
Labels: bug

**Comment by RaphMar2021** [comment] 2023-10-03 10:32
@niels9001 I think the issue has been fixed
