### ISSUE TITLE
Add localizable strings

### ISSUE THREAD

**Issue by Chips1234** [microsoft/WinUI-Gallery#538] opened 2020-08-21 19:46 UTC
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [ ] New sample
- [ ] Addition to existing sample
- [X] Modification to existing sample

Please localize the software into different languages with .resw resource files. Thanks

**Comment by karkarl** [comment] 2024-02-22 19:10
Resolving this as dupe of #787

**Closed by karkarl** 2024-02-22 19:10 UTC
Labels: enhancement
