### ISSUE TITLE
Iconography bug

### ISSUE THREAD

**Issue by GabrielePepe** [microsoft/WinUI-Gallery#1690] opened 2024-12-11 09:06 UTC
### Which version of the app?

WinUI 3 Gallery

### Description

I can't view any information of a icon in iconography section

### Screenshots

![Image](https://github.com/user-attachments/assets/58f555d4-6d52-49f9-93c7-cd433419cd47)

**Comment by AndrewKeepCoding** [comment] 2024-12-11 10:29
Duplicate of #1688.

**Comment by Zakariathr22** [comment] 2024-12-11 19:56
@marcelwgn 
This is a duplicate of #1688 and has been resolved through #1668

**Comment by Jay-o-Way** [comment] 2024-12-11 23:53
OMG so sad the fix didn't make it in the 2.5.0 release :(

**Closed** 2024-12-12 16:03 UTC
Labels: bug, needs-triage

**Comment by Jay-o-Way** [comment] 2024-12-12 19:22
@marcelwgn please tell me this warrants a hotfix. At the moment, the page is useless in public release (!)

**Comment by marcelwgn** [comment] 2024-12-13 07:51
@jay-o-way We are working on releasing a new version in the next few days :)
