### ISSUE TITLE
Application crashes on certain clicks

### ISSUE THREAD

**Issue by akshaybabloo** [microsoft/WinUI-Gallery#1331] opened 2023-08-22 02:25 UTC
### Which version of the app?

WinUI 3 Gallery

### Description

Application crashes when you do the following:

Below flow should be done in `Media`

1. Click on `Image`
2. Then, click on `MediaPlayerElement`
3. Then, click on `PersonPicture`
4. Finally, click `Image` again

UI will crash. I think it is because of `PersonPicture`, but not sure

### Windows version

Windows 10 22H2 (19045)

**Comment by hez2010** [comment] 2023-09-26 17:32
Can reproduce.
```
Exception was thrown: 'Microsoft.UI.Xaml.Markup.XamlParseException' (in WinRT.Runtime.dll)
WinRT Information:The target object with name 'learnMoreGrid' could not be resolved for a Setter. [Line: 44 Position: 114]
XAML parsing failed.
```

**Comment by karkarl** [comment] 2023-11-09 19:24
Resolving this as dupe of #1206

**Closed by karkarl** 2023-11-09 19:24 UTC
Labels: bug
