### ISSUE TITLE
header acts weird with touchpad. quickly scrolled up:

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/WinUI-Gallery#737] opened 2021-07-23 11:07 UTC
**Describe the bug**

Flinging upwards using my touchpad results in the What's New header acting odd. Pictured below.

**Steps to reproduce the bug**

1. Fling upwards using touchpad or finger

**Expected behavior**

**Actual behavior**

**Screenshots**

**Version Info**
- [x] App downloaded from Store 
    - If so, which version? (Found on the Settings page of the app.)
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3preview branch)

**Additional context**

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

![image](https://user-images.githubusercontent.com/51363864/126773606-1f370fd7-fbc7-48df-97d6-17c925afbe04.png)

**Comment by chingucoding** [comment] 2021-08-24 18:05
Can you elaborate what the issue is?

**Comment by Poopooracoocoo** [comment] 2021-08-25 00:21
I don't really care about the issue anymore, let alone Microsoft stuff (from a more-than-user pov)
If I recall correctly, the header looks as it does in the image despite being scrolled to the top. It's not supposed to look like that, transparent and all. It looks like that because I quickly scrolled up using my touchpad. This is likely a WinUI issue so I wouldn't be surprised if it were transferred over there.

**Comment by gregwoo-microsoft** [comment] 2022-01-06 00:23
I can't repro this. Seems like this got fixed. Feel free to reopen this issue if this pops up again.

**Comment by Poopooracoocoo** [comment] 2022-01-06 01:08
@gregwoo-microsoft So while some changes have been made in WinUI and XCG since creating this issue, it still "acts weird". It's the same thing as above, minus the white background. Here's a video of me just flinging my touchpad back and forth. Gee, I really said "open your eyes". But I wouldn't have expected this to have some sort of resolution this much later

https://user-images.githubusercontent.com/51363864/148311722-260e4e8f-00fb-4cfe-951c-be57ab30bea5.mp4

.

**Comment by Poopooracoocoo** [comment] 2022-01-06 03:20
So if I wasn't clear, consider opening this again and maybe transfer it to WinUI? 🙃

**Comment by gregwoo-microsoft** [comment] 2022-01-06 17:11
Ok thanks for sharing the video. I better understand the issue now.

**Comment by chingucoding** [comment] 2023-07-04 18:50
Closing this since the "What's new" header is gone now along the effect shown above.

**Closed by chingucoding** 2023-07-04 18:50 UTC
Labels: bug
