### ISSUE TITLE
Extremely bugged scrolling in iconography section

### ISSUE THREAD

**Issue by GabrielePepe** [microsoft/WinUI-Gallery#1710] opened 2024-12-17 18:04 UTC
### Which version of the app?

WinUI 3 Gallery

### Description

After fixing the source details bug, a new bug arose regarding scrolling (see video).

https://github.com/user-attachments/assets/431be5ef-c39d-4089-8905-a71efbd02a4f

### Windows version

Windows 11 24H2 (26052)

**Comment by Zakariathr22** [comment] 2024-12-17 18:35
This is a duplicate of #1699 

As mentioned in [this comment](https://github.com/microsoft/WinUI-Gallery/issues/1699#issuecomment-2541922787)
> Looks like this issue was caused by an experimental upgrade of WinUI. We're looking into the issue!

**Closed** 2024-12-18 21:42 UTC
Labels: bug, needs-triage
