### ISSUE TITLE
Protocol Activation doesn't work if app is not running

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/WinUI-Gallery#19] opened 2018-12-21 22:26 UTC
**Describe the bug**
If you try and open the app with a protocol link (like `xamlcontrolsgallery:///item/ProgressRing`), it doesn't work unless the app is already open.  If the app isn't open, when it launches, it should still respect the protocol launch and navigate to the section or item in the protocol.

**Steps to reproduce the bug**
1. Make sure app is closed.
2. Hit Win+R and enter `xamlcontrolsgallery:///item/ProgressRing`

**Expected behavior**
App opens and goes to ProgressRing control page.

**Actual behavior**
App opens to home page.
If you repeat the steps with the app open, the app correctly navigates to the page, but this should happen regardless of the current state of the app.

**Version Info**
Gallery version (found on Settings page): 
[e.g. 1.2.4.0]

Windows 10 version:
- [x] Insider Build (18305)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Xbox
- [ ] Mobile
- [ ] Surface Hub
- [ ] IoT

**Comment by stmoy** [comment] 2019-01-02 19:39
Thank you for reporting this!

**Comment by michael-hawker** [comment] 2019-01-03 20:35
No problem, I was looking to provide direct links to some samples, but ran into this.

**Comment by chingucoding** [comment] 2019-08-09 08:40
In version 1.2.8.0 the opposite is the case (on Windows 10 Insider build 18950). See the following GIFs:

Starting without app started using protocol:
![starting-without-app-started](https://user-images.githubusercontent.com/16122379/62765887-68a24500-ba91-11e9-8aa2-d78482cf4314.gif)

Starting with app started using protocol:
![starting-with-app-started](https://user-images.githubusercontent.com/16122379/62765886-68a24500-ba91-11e9-8f24-07cc7bcf546a.gif)

Maybe we should change the issue ?

**Comment by stmoy** [comment] 2019-08-09 17:16
> Starting without app started using protocol:

To help me understand: does this mean that you're seeing the Gallery open to a random page upon launch if not using protocol activation?

**Comment by chingucoding** [comment] 2019-08-09 17:25
Oh missphrased that a bit. What I meant was when the app was not already open. 
The command I entered was: 
xamlcontrolsgallery:///item/ProgressRing
So it opening the ProgressRing page is the correct behaviour. ^^

**Comment by stmoy** [comment] 2019-08-09 17:36
Gotcha, thanks. I'm still a little confused by the GIFs though. Are the below statements accurate?

GIF 1: Opened Gallery using `xamlcontrolsgallery:///item/ProgressRing`
Outcome: App opens to ProgressRing page (correct behavior ✔)
GIF 2: Gallery already open, then run `xamlcontrolsgallery:///item/ProgressRing`
Outcome: App goes to the New Item page (instead of ProgressRing page) ❌

**Comment by chingucoding** [comment] 2019-08-09 17:38
Yes thats correct. That was the behavoiur that I could observe on my machine.

**Comment by stmoy** [comment] 2019-08-09 17:42
Ah, I see! I am seeing the same behavior on my machine as well.

I think there is also a third condition: App is open on the What's New page, then run `xamlcontrolsgallery:///item/ProgressRing`. Outcome: App goes to ProgressRing page (correct behavior ✔)

Our general process is to close issues if they no longer repro and file new issues as we find them. @chingucoding - could you please file a new issue that describes the problem in GIF 2? Then we can close this issue. 

Thank you so much for your investigations and bug fixes!! 🙌

**Comment by chingucoding** [comment] 2019-08-09 17:51
Yes will do! No problem :)

**Comment by chingucoding** [comment] 2019-08-12 10:49
I tested protocol activation on a device running Build 18362 and starting the app with any protocol does not work as expected. No matter if the app is running or not, running the protocol navigates the application to the "New items" page.
Is this something we can fix?

**Comment by stmoy** [comment] 2019-08-12 21:54
> I tested protocol activation on a device running Build 18362 and starting the app with any protocol does not work as expected. 

To clarify, it sounds like this is a change in behavior/regression between builds? I'm on 18956 and it exhibits the semi-correct behavior discussed above. 

Since this code hasn't been changed by the app in a long time, I wonder if it's an issue with the protocol activation service itself. If so:

> Is this something we can fix?

¯\_(ツ)_/¯

If the behavior is mostly correct on the latest versions of Windows, I'm inclined to say that this is a "won't fix" for now.

**Closed as completed** 2019-08-27 01:43 UTC
Labels: enhancement
